### ISSUE TITLE
Missing sub-resolvers on regenetating

### ISSUE THREAD

**Issue by microo8** [vektah/gqlgen#149]
I've implemented the new way of using the lint-friendly small resolvers from #134 
So I have a `ResolverRoot` with all the small resolvers. 

```go
package graph

type MyResolver struct{}

func (r *MyResolver) Query() QueryResolver {
    return new(myQueryResolver)
}

...
```

And everything compiles and runs as expected.

### Expected Behaviour
I've expected that when I need to update the schema and than re-generate the code with `gqlgen`.

### Actual Behavior
The `QueryResolver` interface is declared in `generated.go`, but on re-running the `gqlgen` it is no longer there and it fails on that the interfaces are not declared.

```
/home/micro/Workspace/src/myproject/graph/graph.go:125:28: undeclared name: QueryResolver
/home/micro/Workspace/src/myproject/graph/graph.go:133:31: undeclared name: MutationResolver
```

**Comment by vektah** [comment]
This happens because there's a circular dependency chain.

- Your implementation depends on the generated interfaces
- the generated code depends on something in that package (models perhaps?)

Simplest answer is to split them into separate packages:
```
models/models_gen.go
graph/resolvers.go
graph/generated/generates.go
```

Its a common enough issue though, I wonder if it's worth doing a initial pass to generate empty interface versions of the resolvers to break the loop.

**Comment by microo8** [comment]
Thanks, I figured it out. Now the `models_gen.go` and `generated.go` are in separate packages. Other than the implementation of the interfaces.
